import { createEnumParser, enumValues } from './utils';

/** Each cell is a colored square on the face of the cube. There are 54 cells. */
export enum Cell {
  F = 'F',
  FNW = 'FNW',
  FN = 'FN',
  FNE = 'FNE',
  FE = 'FE',
  FSE = 'FSE',
  FS = 'FS',
  FSW = 'FSW',
  FW = 'FW',
  B = 'B',
  BNW = 'BNW',
  BN = 'BN',
  BNE = 'BNE',
  BE = 'BE',
  BSE = 'BSE',
  BS = 'BS',
  BSW = 'BSW',
  BW = 'BW',
  L = 'L',
  LNW = 'LNW',
  LN = 'LN',
  LNE = 'LNE',
  LE = 'LE',
  LSE = 'LSE',
  LS = 'LS',
  LSW = 'LSW',
  LW = 'LW',
  R = 'R',
  RNW = 'RNW',
  RN = 'RN',
  RNE = 'RNE',
  RE = 'RE',
  RSE = 'RSE',
  RS = 'RS',
  RSW = 'RSW',
  RW = 'RW',
  U = 'U',
  UNW = 'UNW',
  UN = 'UN',
  UNE = 'UNE',
  UE = 'UE',
  USE = 'USE',
  US = 'US',
  USW = 'USW',
  UW = 'UW',
  D = 'D',
  DNW = 'DNW',
  DN = 'DN',
  DNE = 'DNE',
  DE = 'DE',
  DSE = 'DSE',
  DS = 'DS',
  DSW = 'DSW',
  DW = 'DW',
}

export const Cells = enumValues(Cell);
export const parseCell = createEnumParser(Cell);
